### ISSUE TITLE
Bug: Could not find "@double-great/stylelint-a11y/recommended"

### ISSUE THREAD

**Issue by Archinowsk** [double-great/stylelint-a11y#65]
I'm trying to use the recommended config but receive following error:

```
Error: Could not find "@double-great/stylelint-a11y/recommended". Do you need to install the package or use the "configBasedir" option?
    at configurationError (.../node_modules/stylelint/lib/utils/configurationError.mjs:12:49)
    at getModulePath (.../node_modules/stylelint/lib/utils/getModulePath.mjs:29:9)
    at loadExtendedConfig (.../node_modules/stylelint/lib/augmentConfig.mjs:217:21)
    at extendConfig (.../node_modules/stylelint/lib/augmentConfig.mjs:185:25)
    at augmentConfigBasic (.../node_modules/stylelint/lib/augmentConfig.mjs:58:26)
    at augmentConfigFull (.../node_modules/stylelint/lib/augmentConfig.mjs:112:30)
    at Object.transform (.../node_modules/stylelint/lib/getConfigForFile.mjs:52:37)
    at search (...\node_modules\cosmiconfig\dist\Explorer.js:53:54)
    at async search (...\node_modules\cosmiconfig\dist\Explorer.js:71:28)
    at async search (...\node_modules\cosmiconfig\dist\Explorer.js:71:28)
```

`.stylelintrc.js`

```js
module.exports = {
  extends: ["@double-great/stylelint-a11y/recommended"],
  rules: {},
};
```

Command to run:
```
npx stylelint .
```

Happens with NPM and Yarn.

Versions:

 - stylelint 16.2.1
 - @double-great/stylelint-a11y - tested versions 3.0.0, 3.0.1, 3.0.2

OS: Win11

Adding rules directly works, for example this:

```js
module.exports = {
  plugins: ["@double-great/stylelint-a11y"],

  rules: {
    "a11y/media-prefers-reduced-motion": true,
  },
};
```

**Comment by cylewaitforit** [comment]
For `@double-great/stylelint-a11y@2.0.2` we were able to get the recommended list working by using yarn to patch the package.json file to have exports.
``` json
"exports":{
  "." : "./dist/index.js",
  "./recommended": "./recommended.cjs"
},
```

Adding exports for `@double-great/stylelint-a11y@3.0.2` got past the “could not find” error but currently getting a different error that I haven’t been able to solve yet.

``` sh
TypeError: Cannot read properties of undefined (reading 'ignoreFiles')
```

**Comment by cylewaitforit** [comment]
The changes in https://github.com/double-great/stylelint-a11y/pull/71 should fix this.
